### ISSUE TITLE
Changing from ifort to gfortran

### ISSUE THREAD

**Issue by ramirezfranciscof** [nanolebrero/lio#45]
Hey @chopkins906, sorry to bother you but I was adapting all the code so it would compile with gfortran instead of ifort and used the modifications you implemented in your branch as guideline, but I think I am having some troubles with linking to lapack.

Where does your variable $(PACK_LIB_DIR) point to?

**Comment by chopkins906** [comment]
Well, I should start by saying I didn't / still don't know how to generally find and link the lapack libraries ... I would be interested in learning how the best way to do this is.

The PACK_LIB_DIR variable is just assumed to be a user-made variable that points to a directory with all the needed lapack libraries in it.  For my testing, I just made a directory and copied libblas / liblapack (actually maybe you just need liblapack...) into it and set PACK_LIB_DIR to that directory.  Maybe it should just be set to /usr/lib by default, but I think I've seen lapack in different places in different systems...

**Comment by ramirezfranciscof** [comment]
Ok, thanks for the information. I just patched master to do that: search for liblapack in /usr/lib. Though as you say, it would probably be a good idea to look for the regular way to use the lapack libs. Nano also told me that there may be more advanced versions of this libraries available and free.

 I am leaving this open because I consider that this will not be the final implementation; any information related to this can be left here until a decision on a final way to do this is reached.

(Also, for reference, if someone needs to compile with ifort he has to make with "ifort=1" both lioamber and liosolo)

**Comment by manuelF** [comment]
As of c6c23b7d1952863b1f8769c4d2d36671ad5236d2 I can't compile with gfortran 4.6.3 using the default options. In at least `SCF.o` I'm getting a 
```
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c SCF.f -o obj/SCF.o 
SCF.f:11.72:

      use garcha_mod                                                    
                                                                        1
Fatal Error: File 'garcha_mod.mod' opened at (1) is not a GFORTRAN module file
```
error I can't seem to find out why. 

In gfortran 4.9.2 I am getting a different error
```
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c SCF.f -o obj/SCF.o 
Fatal Error: Reading module garcha_mod at line 1 column 2: Unexpected EOF
make[1]: *** [obj/SCF.o] Error 1
```

Any ideas? What are you doing to compile it?

**Comment by chopkins906** [comment]
@manuelF I think if you do a `make clean` first and then rerun `make`, it should recompile the mod files with gfortran.  Those *.mod files are compiler-specific; they're probably left over from a previous compile with ifort - maybe from switching from another branch?

I just tried compiling with a fresh copy of the code and it seems OK.

**Comment by manuelF** [comment]
@chopkins906 Yes, the switch between branches was the culprit.  I am having 2 different issues now with this.

First, the output strings of timers are now quite broken (this was built with gcc 4.6.2 and 4.9.2, and also a problem on ifort 14)
```
m: 523 nco: 118
 nco: 118
<====== read_options ========>
No "gpu_options" file: using defaults
TIMER [choleskyLV]: 261634us.
TIMER [int3memLevel SHIFT is not suportedTotal iter]: 2s. 918057us.
TIMER [principio int3ludgelss]: 65306us.
TIMER [int3luAt line 322 of file int3mem.f]: 112486us.
iteration: 32s. 116044us.
rmm: 74118616s. 634067us. density: 201510518s. 974079us. pot: 155838233s. 568405us. forces: 145583658s. 875843us. resto: 0us. functions: 0us.

XC energy: 0
TIMER [actualiza rmmdiis]: 701027us.
TIMER [dspevcoeffotras cosasiterQM Energy=NO CONVERGENCE AT  ITERATIONSCONVERGED ATITERATIONS]: 335311us.
TIMER [coeffotras cosasiterQM Energy=NO CONVERGENCE AT  ITERATIONSCONVERGED ATITERATIONS]: 151165us.
TIMER [otras cosasiterQM Energy=NO CONVERGENCE AT  ITERATIONSCONVERGED ATITERATIONS]: 45106us.
TIMER [Total iter]: 33s. 543968us.
TIMER [principio int3ludgelss]: 65566us.
TIMER [int3luAt line 322 of file int3mem.f]: 113153us.
iteration: 33s. 673156us.
rmm: 49292328s. 276471us. density: 155910371s. 806499us. pot: 112779281s. 708651us. forces: 92966888s. 963896us. resto: 0us. functions: 0us.
```

Second, there is a race condition on the lioamber Makefile. If I do several ``` make clean; make -j``` in the lioamber/ folder it consistently fails on some module, either garchamod or mathsubs mod. This kind of errors:
```
manuel@daneel:~/lio/lioamber (master) $ make -j cpu=1 time=1 openmp=1 cpu_recompute=0 
mkdir -p obj
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c liomain.f -o obj/liomain.o 
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c liomods/garcha_mod.f -o obj/garcha_mod.o 
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c liomods/garcha_mod.f -o obj/garcha_mod.o
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c mathsubs/mathsubs.f -o obj/mathsubs.o 
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c mathsubs/mathsubs.f -o obj/mathsubs.o
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c TD.f -o obj/TD.o 
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c magnus.f -o obj/magnus.o 
Fatal Error: Can't delete temporary module file 'obj/garcha_mod.mod0': No such file or directory
gfortran  -Iobj -Jobj -cpp -Dpack -fPIC -DG2G -g -O3    -c mulliken.f -o obj/mulliken.o 
make: *** [obj/garcha_mod.mod] Error 1
make: *** Waiting for unfinished jobs....
^Cmake: *** Deleting file `obj/mathsubs.mod'

```

I am guessing some dependencies on the Makefile are not fully specified. When building with ifort does not appear to show this behaviour (maybe it does a late binding to the modules?).

**Comment by nanolebrero** [comment]
El rpoblema es que cuando compilas con -j puede querer compilar algo antes
de que termine de compilar el modulo.
Compilar sin -j es una opción.

2015-02-25 15:13 GMT-03:00 Manuel Ferreria <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
(1) This also happened with ifort before? Or stared happening with ifort now? Could you determine the exact commit in which this started malfunctioning? There were some flags that were deleted when implementing the new makefile scheme; I think most of them I asked here before deleting, but I might have missed one.

(2) I am not familiar with option -j, what does it do?

**Comment by manuelF** [comment]
1. It is quite hard to pinpoint the bug, as previous patches in master are not buildable by themselves (i.e. cf89da8) (shouldn't be possible with the prepush hook but it could happen). At least in late december I remember this wasn't happening. Very likely to do with the changes regarding ifort->gfortran.

2. ```make -j``` does a make in parallel, it permits parallel builds in the project (speeds up the compilation 2-4x). The proper fix would be to add the module dependency (i.e. ```garcha_mod.mod```) to the files that need it, making it a dependency before building. This would assure consistency across builds.

**Comment by chopkins906** [comment]
Ah OK, sorry I fixed the timer issue in the Florida branch a while back ... I thought it was an issue only when compiling the C++ code with gcc, but I guess it's on the Fortran side.  It's a simple fix in g2g/timer.cpp

I've never asked before ... is it OK if I make the change to master? I can understand if you guys only want certain people touching master ;)

**Comment by manuelF** [comment]
@chopkins906 Sure, apply the patch to master and push it. No problem there. Thanks!

**Comment by ramirezfranciscof** [comment]
1. Ok, I guess this might get fixed now. Thanks @chopkins906 !
2. The dependency with modules is explicitly assigned in the file make_depend.mk and as far as I could check all subs that use module X have module X as a dependency (both the .o and the .mod files). I can re-check this tomorrow, but could the problem be elsewhere?

**Comment by ramirezfranciscof** [comment]
(2) @manuelF  Just checked and TD was missing in the list of objects that needed garcha_mod. Just fixed and pushed; I tried 'make -j' myself and seemed to work. Please try and confirm if problem is fixed.

**Comment by manuelF** [comment]
@ramirezfranciscof No, it's still not fixed. Don't bother with it, I am looking into it since it seems to be a finicky race condition trying to build twice garcha_mod. I'll try to get a fix for this week.

**Comment by ramirezfranciscof** [comment]
@manuelF Oh, ok. That is odd; it seemed to compile alright in my machine.

Let me know if there is something you need me to do or check.

**Comment by manuelF** [comment]
`rc` branch defaults to GNU gcc and compiles fine with Intel icc too.
